package dk.brics.jwig;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Classes marked with regererable represent objects that live in the jwig cache and may be evicted
 * at any point. Such objects may need to be reconstructed by issuing a request to the original URL
 * for which they were created and the objects must behave correctly in this case. See the <em>Page regeneration</em>
 * section the JWIG manual.
 * <p>
 * In particular event handlers and submit handlers may need be regenerated by the JWIG runtime system.
 */
@Retention(RetentionPolicy.SOURCE)
@Documented
public @interface Regenerable {
}
