package dk.brics.jwig.server.cache;

import dk.brics.jwig.Response;

/**
 * The cache is responsible for caching responses, generated by JWIG and sent to the client.
 */
public interface Cache {
    /**
     * Clears the cache.
     */
    void destroy();

    /**
     * Looks for a cached response for the given URL.
     * If found, the response is moved to the front of the queue.
     */
    Response get(String url);

    /**
     * Caches the given response.
     * Should only be used for responses with status 200.
     */
    void put(String url, Response r);

    /**
     * Removes the given response and its handlers from the cache.
     */
    void remove(String url);

}
